#!/usr/bin/env bash
# Installs facelock system-wide, following standard Linux (FHS) paths:
#   /opt/facelock              - self-contained venv + installed package
#   /usr/local/bin/facelock-*  - symlinks onto PATH for locally-installed software
#   ~<user>/.config/systemd/user/facelock-monitor.service - per-user service unit
#
# Must be run with sudo as your normal login user (not as a bare root login),
# so it knows whose systemd --user session and home directory to target.
set -euo pipefail

if [[ $EUID -ne 0 || -z "${SUDO_USER:-}" ]]; then
    echo "Run this with sudo as your normal user, e.g.:" >&2
    echo "  sudo ./install.sh" >&2
    exit 1
fi

REAL_USER="$SUDO_USER"
REAL_HOME="$(getent passwd "$REAL_USER" | cut -d: -f6)"
REAL_UID="$(id -u "$REAL_USER")"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PREFIX=/opt/facelock
BIN_DIR=/usr/local/bin
UNIT_NAME=facelock-monitor.service
UNIT_DST="$REAL_HOME/.config/systemd/user/$UNIT_NAME"

echo "This will install facelock for user '$REAL_USER':"
echo "  code + venv -> $PREFIX"
echo "  commands    -> $BIN_DIR/facelock-enroll, $BIN_DIR/facelock-monitor"
echo "  service     -> $UNIT_DST"
read -rp "Proceed? [y/N] " reply
[[ "$reply" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 1; }

if ! python3 -m venv --help >/dev/null 2>&1; then
    echo "python3's venv module isn't available. Install it first, e.g.:" >&2
    echo "  sudo apt install python3-venv" >&2
    exit 1
fi

echo "==> Creating venv at $PREFIX and installing facelock into it"
mkdir -p "$PREFIX"
python3 -m venv "$PREFIX/venv"
"$PREFIX/venv/bin/pip" install --upgrade pip -q
"$PREFIX/venv/bin/pip" install "$REPO_DIR" -q
chmod -R a+rX "$PREFIX"

echo "==> Linking commands into $BIN_DIR"
ln -sf "$PREFIX/venv/bin/facelock-enroll" "$BIN_DIR/facelock-enroll"
ln -sf "$PREFIX/venv/bin/facelock-monitor" "$BIN_DIR/facelock-monitor"

echo "==> Installing systemd --user service for $REAL_USER"
sudo -u "$REAL_USER" mkdir -p "$(dirname "$UNIT_DST")"
sed "s|@VENV_BIN@|$BIN_DIR|" "$REPO_DIR/packaging/$UNIT_NAME" > "$UNIT_DST"
chown "$REAL_USER":"$REAL_USER" "$UNIT_DST"
sudo -u "$REAL_USER" XDG_RUNTIME_DIR="/run/user/$REAL_UID" systemctl --user daemon-reload

FACE_FILE="$REAL_HOME/.local/share/facelock/known_face.npy"
if [[ -f "$FACE_FILE" ]]; then
    echo "==> Existing enrolled face found, enabling and starting the service now"
    sudo -u "$REAL_USER" XDG_RUNTIME_DIR="/run/user/$REAL_UID" systemctl --user enable --now "$UNIT_NAME"
else
    echo
    read -rp "No enrolled face found. Enroll now (uses your webcam)? [y/N] " enroll_reply
    if [[ "$enroll_reply" =~ ^[Yy]$ ]]; then
        sudo -u "$REAL_USER" -H "$BIN_DIR/facelock-enroll"
        sudo -u "$REAL_USER" XDG_RUNTIME_DIR="/run/user/$REAL_UID" systemctl --user enable --now "$UNIT_NAME"
    else
        sudo -u "$REAL_USER" XDG_RUNTIME_DIR="/run/user/$REAL_UID" systemctl --user enable "$UNIT_NAME"
        echo "Service enabled but not started. Run 'facelock-enroll' as $REAL_USER, then:"
        echo "  systemctl --user start $UNIT_NAME"
    fi
fi

echo "==> Writing uninstaller to $PREFIX/uninstall.sh"
cat > "$PREFIX/uninstall.sh" <<EOF
#!/usr/bin/env bash
# Generated by install.sh — reverses exactly what that run installed.
set -euo pipefail

if [[ \$EUID -ne 0 ]]; then
    echo "Run this with sudo: sudo $PREFIX/uninstall.sh" >&2
    exit 1
fi

echo "==> Stopping and removing the systemd --user service for $REAL_USER"
sudo -u "$REAL_USER" XDG_RUNTIME_DIR="/run/user/$REAL_UID" systemctl --user disable --now "$UNIT_NAME" 2>/dev/null || true
rm -f "$UNIT_DST"
sudo -u "$REAL_USER" XDG_RUNTIME_DIR="/run/user/$REAL_UID" systemctl --user daemon-reload || true

echo "==> Removing $BIN_DIR/facelock-enroll and $BIN_DIR/facelock-monitor"
rm -f "$BIN_DIR/facelock-enroll" "$BIN_DIR/facelock-monitor"

echo "==> Removing $PREFIX"
rm -rf "$PREFIX"

echo "Note: your enrolled face and config were left in place at:"
echo "  $REAL_HOME/.local/share/facelock/"
echo "  $REAL_HOME/.config/facelock/"
echo "Remove those yourself if you want a completely clean uninstall."
EOF
chmod +x "$PREFIX/uninstall.sh"

echo
echo "Done. Uninstall anytime with: sudo $PREFIX/uninstall.sh"
